MÓDULO 1 - IMPORTANDO AS BIBLIOTECAS

In [2]:
# sempre a primeira tela do nootbook, importar o vai usar

import pandas as pd
import re
from datetime import datetime

# confirmar importações

print(' pandas versão:', pd.__version__)
print(' Bbt import comk sucesso')

 pandas versão: 3.0.2
 Bbt import comk sucesso

MÓDULO 2 - LENDO ARQUIVO .CSV

In [3]:
#pd_read_csv() - para ler o .cvs
#CAMINHO do .csv (Nomeia o caminho do arquivo)

CAMINHO = r'C:\Users\ENG PC\turma-visualizacao-de-dados\alunos\jonatas_mag\Semana_04\base_rh.csv'

df = pd.read_csv(
    CAMINHO,
    sep=";",            #separador de colunas a ser usado
    encoding="cp1252",   #encode do windos para acentos
    decimal=","         #Separador de casas decimais
)

print('Dados Carregados')
print(f' Total de linhas: {df.shape[0]}')
print(f' Total de Colunas: {df.shape[1]}')

Dados Carregados
 Total de linhas: 1000
 Total de Colunas: 10

MÓDULO 3 - PRIMEIRAS OLHADAS NOS DADOS

In [6]:
df.head(5)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [8]:
df.tail(5)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [9]:
print('Colunas do Dataset')
print(df.columns.tolist())

Colunas do Dataset
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

MÓDULO 4 - DISGNÓSTICO: TIPOS E NULOS

In [15]:
print(' === RESUMO GERAL DA BASE === ')

df.info()

 === RESUMO GERAL DA BASE ===
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [23]:
print('Total de nulos por coluna')
df.isnull().sum()


print((df.isnull().sum() / len(df) *100).round(2))

Total de nulos por coluna
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

MÓDULO 5 - ESTATÍSTICA DAS COLUNAS NUMÉRICAS

In [32]:
df.describe()

df.describe().round(2)

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

MÓDULO 6 - EXPLORANDO COLUNAS CATEGÓRICAS

In [40]:
print("Volores unicos por coluna:"), df.nunique()

print("Repetiçõe:")
df.value_counts()

Volores unicos por coluna:
Repetiçõe:

ID_Funcionario  Nome                 Departamento  Cargo        Salario   Data_Admissao  Genero  Idade  Estado_Civil  Status
1               Julia Nunes          Logística     Coordenador  9088.34   13/08/2024     F       43     Solteiro      Inativo    1
2               Sr. Gustavo Duarte   TI            Gerente      8155.98   29/04/2017     F       59     Solteiro      Inativo    1
3               Srta. Mariana Cunha  RH            Coordenador  14027.93  11/12/2024     F       27     Divorciado    Ativo      1
4               Ana Sophia da Cruz   Produção      Técnico      6647.97   16/06/2019     M       50     Casado        Inativo    1
5               Dr. Nicolas Pinto    Produção      Gerente      8730.19   29/03/2019     F       62     Casado        Inativo    1
                                                                                                                                ..
996             Matheus Aragão       Financeiro    Analista     11389.03  06/05/2022     F       26     Viúvo         Ativo      1
997             Ryan Martins         Financeiro    Analista     14060.42  05/06/2023     F       37     Viúvo         Ativo      1
998             Isabelly Ferreira    TI            Gerente      2348.73   29/12/2023     F       58     Solteiro      Inativo    1
999             Thales Farias        Produção      Analista     9430.62   25/12/2019     M       41     Solteiro      Ativo      1
1000            Sra. Maysa Costela   Produção      Técnico      12549.72  14/11/2022     M       46     Viúvo         Inativo    1
Name: count, Length: 1000, dtype: int64

In [4]:
for col in ['Departamento', 'Cargo', 'Genero', 'Status', 'Estado_Civil']:
    print(f'\n--{col}--')
    print(df[col].value_counts())

--Departamento--
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

--Cargo--
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

--Genero--
Genero
F    510
M    490
Name: count, dtype: int64

--Status--
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

--Estado_Civil--
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64