In [19]:
# MÓDULO 1 - IMPORTANDO AS BIBLIOTECAS
# sempre a primeira tela do nootbook, importar o vai usar

import pandas as pd
import re
import numpy as np
from datetime import datetime

# confirmar importações
print(' pandas versão:', pd.__version__)
print(' Bibliotecas importadas com sucesso')

 pandas versão: 3.0.2
 Bibliotecas importadas com sucesso

In [3]:
# MÓDULO 2 - LENDO ARQUIVOS .CSV

# pd_read_csv() - para ler o .cvs
# CAMINHO do .csv (Nomeia o caminho do arquivo)

CAMINHO = r'C:\Users\ENG PC\turma-visualizacao-de-dados\alunos\jonatas_mag\Semana_04\base_rh.csv'

df = pd.read_csv(
    CAMINHO,
    sep=";",            #separador de colunas a ser usado
    encoding="cp1252",   #encode do windos para acentos
    decimal=","         #Separador de casas decimais
)

print('Dados Carregados')
print(f'Total de linhas e Colunas: {df.shape[0]}, {df.shape[1]}')

Dados Carregados
Total de linhas e Colunas: 1000, 10

In [ ]:
# MÓDULO 3 - PRIMEIRAS OLHADAS NOS DADOS

df.head(5)   # Mostra as primeiras () linhas iniciais do DataFrame

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [ ]:
df.tail(5)  # Mostra as últimas () linhas do DataFrame

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [ ]:
print('Colunas do Dataset')
df.columns.tolist()  # Lista as colunas do DataFrame
print(df.columns.tolist())  # Imprime a lista de colunas do DataFrame NO MODELO PYTON

Colunas do Dataset
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [11]:
# MÓDULO 4 - DIAGNÓSTICO: TIPOS E NULOS

print(' === RESUMO GERAL DA BASE === ')
print()
df.info()

 === RESUMO GERAL DA BASE ===

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [13]:
print('Total de nulos por coluna')
print(df.isnull().sum())

print()
print('Total de nulos por coluna em %')
print((df.isnull().sum() / len(df) *100).round(2))

Total de nulos por coluna
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

Total de nulos por coluna em %
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [ ]:
# MÓDULO 5 - ESTATÍSTICA DAS COLUNAS EM NÚMEROS

df.describe()       # Estatística descritiva das colunas numéricas do DataFrame

df.describe().round(2)     # Estatística descritiva arredondada para 2 casas decimais

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [ ]:
# MÓDULO 6 - EXPLORANDO COLUNAS CATEGÓRICAS

print("Valores únicos por coluna:")
print(df.nunique())

print()

print("Explorar faixa de salários:")
print(df['Salario'].value_counts())    # Contagem de valores únicos na coluna 'Salario'

Valores únicos por coluna:
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

Explorar faixa de salários:

Salario
9088.34     1
8155.98     1
14027.93    1
6647.97     1
8730.19     1
           ..
11389.03    1
14060.42    1
2348.73     1
9430.62     1
12549.72    1
Name: count, Length: 1000, dtype: int64

In [33]:
for col in ['Departamento', 'Cargo', 'Genero', 'Status', 'Estado_Civil']:
    print(f'\n{col} - Contagem de valores únicos:')
    print(df[col].value_counts())

Departamento - Contagem de valores únicos:
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

Cargo - Contagem de valores únicos:
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

Genero - Contagem de valores únicos:
Genero
F    510
M    490
Name: count, dtype: int64

Status - Contagem de valores únicos:
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

Estado_Civil - Contagem de valores únicos:
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64

In [34]:
# MÓDULO 7 - SELECIONANDO COLUNAS E FILTRANDO LINHAS

df['Nome'].head(5)  # Seleciona a coluna 'Nome' e mostra as primeiras linhas

0            Julia Nunes
1     Sr. Gustavo Duarte
2    Srta. Mariana Cunha
3     Ana Sophia da Cruz
4      Dr. Nicolas Pinto
Name: Nome, dtype: str

In [40]:
# Seleciona várias colunas e mostra as primeiras linhas

df[['Nome', 'Departamento', 'Cargo', 'Salario', 'Status']].head(5)

                  Nome Departamento        Cargo   Salario   Status
0          Julia Nunes    Logística  Coordenador   9088.34  Inativo
1   Sr. Gustavo Duarte           TI      Gerente   8155.98  Inativo
2  Srta. Mariana Cunha           RH  Coordenador  14027.93    Ativo
3   Ana Sophia da Cruz     Produção      Técnico   6647.97  Inativo
4    Dr. Nicolas Pinto     Produção      Gerente   8730.19  Inativo

In [39]:
# LISTA SIMPLES: ATIVOS E INATIVOS

ativos = df[df['Status'] == 'Ativo']
# inativos = df[df['Status'] == 'Inativo']

print(f' Total de funcionários: {len(df)}')
print(f' Funcionários ativos: {len(ativos)}')
print(f' Funcionários inativos: {len(df) - len(ativos)}')

 Total de funcionários: 1000
 Funcionários ativos: 515
 Funcionários inativos: 485

In [49]:
# LISTA COMPOSTA COM DUAS CONDIÇÕES

# Listar os Gerentes de TI
gerentes_ti = df[
    (df['Cargo'] == 'Gerente') & (df['Departamento'] == 'TI')
]

print(f' Total de gerentes de TI: {len(gerentes_ti)}')
print()
gerentes_ti[['Nome', 'Salario', 'Status', 'Data_Admissao']]

 Total de gerentes de TI: 31

                            Nome   Salario   Status Data_Admissao
1             Sr. Gustavo Duarte   8155.98  Inativo    29/04/2017
49             Benjamin da Costa   9766.01  Inativo    27/04/2024
130             Catarina Costela   9597.83  Inativo    03/07/2023
131                Laura Cardoso   7364.46  Inativo    29/06/2018
175                Maria Cardoso  12127.27  Inativo    22/05/2024
187            Ana Júlia Cardoso   8738.63    Ativo    30/05/2021
247                  Ian Pereira   2395.32    Ativo    10/05/2019
273            Ana Clara Peixoto   7301.14    Ativo    16/11/2019
296               Augusto Santos   8237.80  Inativo    26/08/2021
307              Manuela Barbosa   7015.91    Ativo    21/06/2017
323             Antônio Oliveira   5273.24    Ativo    22/08/2018
393          Luiz Gustavo da Luz   2543.19  Inativo    09/10/2015
414                 Stella Costa  11718.30    Ativo    09/05/2023
422                Bryan da Cruz  11790.21    Ativo    08/02/2021
426               Emilly Freitas   5147.62  Inativo    10/05/2018
463            Brenda Nascimento   5429.24    Ativo    25/08/2018
493                  Sofia Sales   4941.24  Inativo    15/08/2023
533              Manuela Cardoso   5305.96  Inativo    21/01/2017
607          Luiz Henrique Souza   4398.17    Ativo    21/11/2015
634               Bruna da Cunha   3423.93  Inativo    17/12/2024
650                 Alícia Porto   9547.18  Inativo    18/12/2024
676               Bianca da Cruz   7903.06  Inativo    04/10/2024
691  Sra. Maria Fernanda Freitas   2686.67    Ativo    15/09/2019
707              Emanuelly Souza   8305.81  Inativo    26/03/2019
724                Olivia Moraes   3124.24  Inativo    25/05/2018
841                Bernardo Lima   6149.05    Ativo    24/04/2024
886         Sra. Caroline Araújo   6750.44  Inativo    30/04/2025
891            Ana Clara Moreira  14523.10    Ativo    06/01/2025
909                  Luna Novaes   3106.49  Inativo    17/08/2025
927            Valentina Cardoso  10602.13    Ativo    04/06/2023
997            Isabelly Ferreira   2348.73  Inativo    29/12/2023

In [57]:
# LISTA COM VÁRIAS CONDIÇÕES

# Listar os gerentes de TI que estão ativos
gerentes_ativos = df[
    ((df['Status'] == 'Ativo') &
     (df['Cargo'] == 'Gerente') &
     (df['Departamento'] == 'TI'))
]

# Listar os gerentes de TI que estão inativos
gerentes_inativos = df[
    ((df['Status'] == 'Inativo') &
     (df['Cargo'] == 'Gerente') &
     (df['Departamento'] == 'TI'))
]

print(f' Gerentes de TI ativos: {len(gerentes_ativos)}')
print(f' Gerentes de TI inativos: {len(gerentes_inativos)}')

 Gerentes de TI ativos: 13
 Gerentes de TI inativos: 18

In [54]:
# Estatísticas rápidas de uma coluna numérica

print(f' Salário médio : R$ {df["Salario"].mean():.2f}')        # Média salarial
print(f' Salário máximo : R$ {df["Salario"].max():.2f}')        # Salário máximo
print(f' Salário mínimo : R$ {df["Salario"].min():.2f}')        # Salário mínimo
print(f' Salário mediano : R$ {df["Salario"].median():.2f}')    # Salário mediano

 Salário médio : R$ 8579.95
 Salário máximo : R$ 14954.51
 Salário mínimo : R$ 2000.71
 Salário mediano : R$ 8571.13

In [ ]:
# MÓDULO 8 - EXPORTANDO PARA JSON, EXCEL E CSV

[
    { "Nome": "João Silva", "Departamento": "Logisitica", "Salário": 9088,34},
    { "Nome": "Maria Oliveira", "Departamento": "TI", "Salário": 12000,00}
]

SyntaxError: ':' expected after dictionary key (3887934065.py, line 3)

In [70]:
import json     # Biblioteca para trabalhar com arquivos JSON (Java Script Object Notation)

df.to_json(
    'base_rh.json',     # Nome do arquivo de saída
    orient='records',   # Orientação dos dados (cada linha é um registro)
    force_ascii=False,  # Permite caracteres acentuados no JSON
    indent=2             # Escreve cada registro em uma linha separada
)

print(' Base_rh.json exportada com sucesso!')
df_json = pd.read_json('base_rh.json')           # Lê o arquivo JSON de volta para confirmação
print(f' Linhas lidas do JSON: {len(df_json)}')

 Base_rh.json exportada com sucesso!
 Linhas lidas do JSON: 1000

In [75]:
# Vizualizando os 2 primeiros registros do JSON para confirmação

with open('base_rh.json', 'r', encoding='utf-8') as f:
    amostra = json.load(f)
print('\nPrimeiros registros do JSON:')
print(json.dumps(amostra[:2], ensure_ascii=False, indent=2))

Primeiros registros do JSON:
[
  {
    "ID_Funcionario": 1,
    "Nome": "Julia Nunes",
    "Departamento": "Logística",
    "Cargo": "Coordenador",
    "Salario": 9088.34,
    "Data_Admissao": "13/08/2024",
    "Genero": "F",
    "Idade": 43,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  },
  {
    "ID_Funcionario": 2,
    "Nome": "Sr. Gustavo Duarte",
    "Departamento": "TI",
    "Cargo": "Gerente",
    "Salario": 8155.98,
    "Data_Admissao": "29/04/2017",
    "Genero": "F",
    "Idade": 59,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  }
]

In [ ]:
#MÓDULO 9 - EXPORTANDO PARA EXCEL
# Precisa ter o Excell instalado para usar o to_excel()
# Instala com pip install openpyxl

# Fazendo a exportação completa para Excel
df.to_excel(
    'base_rh.xlsx',     # Nome do arquivo de saída
    index=False,        # Não inclui o índice do DataFrame no Excel
    sheet_name='Funcionarios'  # Nome da planilha dentro do arquivo Excel
)
print(' Base_rh.xlsx (Aba Única) exportada com sucesso!')

 Base_rh.xlsx (Aba Única) exportada com sucesso!

In [77]:
# Exportação avançada para Excel com múltiplas abas
with pd.ExcelWriter('base_rh_por_departamento.xlsx', engine='openpyxl') as writer:
    df.to_excel(writer, sheet_name='Todos', index=False)         # Aba com todos os funcionários
for depto in sorted(df['Departamento'].unique()):                # Para cada departamento único, cria uma aba específica
    df_depto = df[df['Departamento'] == depto]                   # Filtra o DataFrame para o departamento atual
    nome_aba = depto[:31]                                        # O nome da aba no Excel com limite de 31 caracteres
    df_depto.to_excel(writer, sheet_name=nome_aba, index=False)  # Escreve a aba específica para o departamento
    print(f' Aba "{nome_aba}": {len(df_depto)} registros')

print('\n Base_rh_por_departamento.xlsx (Múltiplas Abas) gerada')

 Aba "Financeiro": 189 registros
 Aba "Logística": 156 registros
 Aba "Produção": 182 registros
 Aba "RH": 166 registros
 Aba "TI": 147 registros
 Aba "Vendas": 160 registros

 Base_rh_por_departamento.xlsx (Múltiplas Abas) gerada

In [83]:
# MÓDULO 10 - O DTATIME BÁSICO

# strptime() - converte string para datetime
# strftime() - converte datetime para string
# %d - dia do mês (01 a 31)
# %m - mês (01 a 12)
# %Y - ano com 4 dígitos (2024)
# %H - hora (00 a 23)
# %M - minuto (00 a 59)
# %B - nome completo do mês (Janeiro, Fevereiro, etc.)

from datetime import datetime, timedelta

data_texto = '13/08/2024' # Data em formato de string
data_obj = datetime.strptime(data_texto, '%d/%m/%Y')  # Converte a string para um objeto datetime usando o formato especificado

print(f' Data original (string): {data_texto}')
print(f' Data convertida (datetime): {data_obj}')
print(f' Tipo do objeto: {type(data_obj)}')

print(' Data transformada em string novamente com sucesso')

 Data original (string): 13/08/2024
 Data convertida (datetime): 2024-08-13 00:00:00
 Tipo do objeto: <class 'datetime.datetime'>
 Data transformada em string novamente com sucesso

In [88]:
# String transformada em datetime novamente usando strftime()

formatado = data_obj.strftime('%d de %B de %Y')  # Converte o objeto datetime 13 de Agosto de 2024
print(f'Data formatada: {formatado}')

# Trabalhando partes da data
print(f'Ano: {data_obj.year}')
print(f'Mes: {data_obj.month}')
print(f'Dia: {data_obj.day}')

# OBS: timedelta() - para calcular diferenças entre datas ou adicionar/subtrair dias, meses, anos, etc.
diferenca = datetime.today() - data_obj  # Calcula a diferença entre a data atual e a data_obj
print(f'Diferença em dias: {diferenca.days} dias')
print(f'Diferença em anos (aproximada): {diferenca.days / 365.25:.1f} anos')

Data formatada: 13 de agosto de 2024
Ano: 2024
Mes: 8
Dia: 13
Diferença em dias: 634 dias
Diferença em anos (aproximada): 1.7 anos

In [89]:
hoje = datetime.today()  # Data e hora atual

diferenca = hoje - data_obj  # Calcula a diferença entre a data atual
print(f'Data de Admissão    : {data_texto}')
print(f'Hoje                : {hoje.strftime("%d/%m/%Y")}')
print(f'Diferença em dias   : {diferenca.days} dias')
print(f'Diferença em anos   : {diferenca.days / 365.25:.1f} anos')

Data de Admissão    : 13/08/2024
Hoje                : 09/05/2026
Diferença em dias   : 634 dias
Diferença em anos   : 1.7 anos

In [112]:
# MÓDULO 11 - CONVERTENDO A COLUNA INTEIRA pd.to_datetime()

print(f'Formato Anterior: {df["Data_Admissao"].dtype}')
print(f'Exemplo de valor: {df["Data_Admissao"].iloc[0]}')

print()

# Criandop uma cópia da df para não alterar a original
# Entregar uma df_limpo através de uma df.copy()
df_limpo = df.copy()

df_limpo["Data_Admissao"] = pd.to_datetime(
    df_limpo["Data_Admissao"],
    format='%d/%m/%Y', # Especifica o formato da data
    errors='coerce'    # Converte valores inválidos para NaT (Not a Time)
)

print(f'Formato Depois: {df_limpo["Data_Admissao"].dtype}')
print(f'Valor convertido: {df_limpo["Data_Admissao"].iloc[0]}')
print(f'Número de datas inválidas convertidas para NaT: {df_limpo["Data_Admissao"].isna().sum()}')

Formato Anterior: str
Exemplo de valor: 13/08/2024

Formato Depois: datetime64[us]
Valor convertido: 2024-08-13 00:00:00
Número de datas inválidas convertidas para NaT: 0

In [126]:
# MÓDULO 12 - EXTRAINDO INFORMAÇÕES DA DATA - ACESSOR .dt

df_limpo['Ano_Admissao'] = df_limpo['Data_Admissao'].dt.year
df_limpo['Mes_Admissao'] = df_limpo['Data_Admissao'].dt.month
df_limpo['Trimestre'] = df_limpo['Data_Admissao'].dt.quarter

# Data atual no formato pandas
hoje_ts = pd.Timestamp.today()
df_limpo['Tempo_Casa_Anos'] = (
    (hoje_ts - df_limpo['Data_Admissao']).dt.days / 365.25
).round(1)

# Resultado
cols = ['Nome', 'Data_Admissao', 'Ano_Admissao', 'Mes_Admissao', 'Trimestre', 'Tempo_Casa_Anos']
print(df_limpo[cols].head(10))

                   Nome Data_Admissao  Ano_Admissao  Mes_Admissao  Trimestre  \
0           Julia Nunes    2024-08-13          2024             8          3
1    Sr. Gustavo Duarte    2017-04-29          2017             4          2
2   Srta. Mariana Cunha    2024-12-11          2024            12          4
3    Ana Sophia da Cruz    2019-06-16          2019             6          2
4     Dr. Nicolas Pinto    2019-03-29          2019             3          1
5         Marcela Costa    2024-07-23          2024             7          3
6  João Miguel da Costa    2021-11-11          2021            11          4
7     Gabrielly Cardoso    2022-04-26          2022             4          2
8           Raul da Paz    2022-11-30          2022            11          4
9   Davi Lucca Teixeira    2020-06-29          2020             6          2

   Tempo_Casa_Anos
0              1.7
1              9.0
2              1.4
3              6.9
4              7.1
5              1.8
6              4.5
7              4.0
8              3.4
9              5.9

In [ ]:
# MÓDULO 13 - CRIANDO MINHA PRIMEIRA FUNÇÃO

def nome_da_funcao(parametros):
    # Bloco de código que realiza uma tarefa específica
    resultado = parametros * 2  # Exemplo de operação
    return resultado  # Retorna o resultado da função

# def - define a função
# parametro - valor de entrada da função
# return - valor de saída da função
# A identação (4 espaços) é fundamental para definir o bloco de código

# Exemplo de uso da função
resultado = nome_da_funcao(5)
print(f'O resultado da função é: {resultado}')

O resultado da função é: 10

In [116]:
# Criar a função que classifica o tempo de casa em categorias
# Facilita a interação com Gráficos e Power BI

def classificar_tempo(anos):
    """
    Recebe: anos (número) -- o tempo de casa do funcionário
    Retorna: uma categoria em texto (string)
    """
    # pd.isna() - para verificar se o valor é NaN (Not a Number)
    if pd.isna(anos):
        return 'Sem data'
    elif anos < 1:
        return 'Menos de 1 ano'
    elif anos < 3:
        return 'Entre 1 a 3 anos'
    elif anos < 5:
        return 'Entre 3 a 5 anos'
    else:
        return 'Mais de 5 anos'

# Testar a função com valores indivuduais antes e aplicar o dataframe
print('Testando a função:')
print(f'    0.5 anos -> "{classificar_tempo(0.5)}"')
print(f'    2.1 anos -> "{classificar_tempo(2.1)}"')
print(f'    4.8 anos -> "{classificar_tempo(4.8)}"')
print(f'    9.0 anos -> "{classificar_tempo(8.0)}"')

Testando a função:
    0.5 anos -> "Menos de 1 ano"
    2.1 anos -> "Entre 1 a 3 anos"
    4.8 anos -> "Entre 3 a 5 anos"
    9.0 anos -> "Mais de 5 anos"

In [137]:
# .apply(função) - para aplicar a função em toda a coluna do DataFrame
# É como fazer um loop para cada linha, mas de forma otimizada e rápida usando o poder do pandas

# Imprime a lista de colunas presentes no df_
print(df_limpo.columns)

df_limpo['Faixa_Tempo_Casa'] = df_limpo['Tempo_Casa_Anos'].apply(classificar_tempo)

print('Distribuição por faixa de tempo de casa:')
print(df_limpo['Faixa_Tempo_Casa'].value_counts())

Index(['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario',
       'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status',
       'Ano_Admissao', 'Mes_Admissao', 'Trimestre', 'Tempo_de_casa_em_anos',
       'Tempo_Casa_Anos', 'Faixa_Tempo_Casa'],
      dtype='str')
Distribuição por faixa de tempo de casa:
Faixa_Tempo_Casa
Mais de 5 anos      537
Entre 3 a 5 anos    217
Entre 1 a 3 anos    213
Menos de 1 ano       33
Name: count, dtype: int64

In [132]:
# MÓDULO 14 - FILTRAR POR PERIODO DE DATAS
# pd.dataoffset(years=1) - para criar um deslocamento de 1 ano

hoje = pd.Timestamp.today() 

# Pontos de corte
um_ano_atras = hoje - pd.DateOffset(years=1)
cinco_anos_atras = hoje - pd.DateOffset(years=5)
uma_decada_atras = hoje - pd.DateOffset(years=10)

# Filçtrar por periodo
novos     = df_limpo[df_limpo['Data_Admissao'] >= um_ano_atras]
veteranos = df_limpo[df_limpo['Data_Admissao'] < cinco_anos_atras]
senior    = df_limpo[df_limpo['Data_Admissao'] < uma_decada_atras]

print(f'Admitidos no último ano     : {len(novos)} funcionários')
print(f'Veteranos (5+ anos de casa) : {len(veteranos)} funcionários')
print(f'Sênior (10+ anos de casa)   : {len(senior)} funcionários')

print()

print('Salário médio:')
print(f'    Novos     : R$ {novos["Salario"].mean():.2f}')
print(f'    Veteranos : R$ {veteranos["Salario"].mean():.2f}')
print(f'    Sênior    : R$ {senior["Salario"].mean():.2f}')

Admitidos no último ano     : 38 funcionários
Veteranos (5+ anos de casa) : 533 funcionários
Sênior (10+ anos de casa)   : 63 funcionários

Salário médio:
    Novos     : R$ 8914.83
    Veteranos : R$ 8600.15
    Sênior    : R$ 8569.68

In [133]:
# MÓDULO 15 - AGRUPAMENTO COM .groupby()
# .groupby() - Tabela dinamica do Excel para agrupar os dados por uma ou mais colunas e calcular estatísticas para cada grupo
# Ex.: df.groupby('Coluna a ser agrupada')['coluna a ser calculada'].função()

# FORMULA:
# .mean()             → calcula a média de cada grupo
# .round(2)           → arredonda para 2 casas
# .sort_values(...)   → ordena do maior para o menor
# ascending=False     → decrescente (False = do maior para o menor)

print('Salário médio por departamento:')
print(
    df_limpo.groupby('Departamento')['Salario']
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

Salário médio por departamento:
Departamento
Produção      8968.73
Logística     8881.66
RH            8791.58
Financeiro    8333.12
Vendas        8317.08
TI            8142.91
Name: Salario, dtype: float64

In [135]:
# Tempo médio de casa por departamento
media_depto = (df_limpo.groupby('Departamento')['Tempo_Casa_Anos']
    .mean()
    .round(1)
    .sort_values(ascending=False)
    .rename('Média_Anos')
    .reset_index()
)

print('Tempo médio de casa por departamento:')
print(media_depto.to_string(index=False))

# .idexmax() - para encontrar o índice do valor máximo em cada grupo
maior = media_depto.set_index('Departamento')['Média_Anos'].idxmax()
manor = media_depto.set_index('Departamento')['Média_Anos'].idxmin()
print(f'\n-> Maior Retenção: {maior}')
print(f'-> Menor Retenção: {manor}')

Tempo médio de casa por departamento:
Departamento  Média_Anos
          RH         5.8
      Vendas         5.7
    Produção         5.5
          TI         5.5
   Logística         5.3
  Financeiro         5.1

-> Maior Retenção: RH
-> Menor Retenção: Financeiro

In [139]:
# Histórico completo de Admissão por Ano

# .size() - para contar o número de registros em cada grupo
# .start_index() - para acessar o valor do grupo (ano) em cada linha do resultado

por_ano = (
    df_limpo.groupby('Ano_Admissao')
    .size()
    .rename('Admissoes')
    .reset_index()
    .dropna()
)

print('Admissões por ano:')
for _, row in por_ano.iterrows():   # Itera sobre cada linha do DataFrame
    barra = '█' * int(row['Admissoes'] / 5)  # Cria uma barra proporcional ao número de admissões
    print(f"  {int(row['Ano_Admissao'])}: {barra} {row['Admissoes']:>4} {barra}")

Admissões por ano:
  2015: ██████   33 ██████
  2016: █████████████████   87 █████████████████
  2017: ███████████████████   99 ███████████████████
  2018: █████████████████   89 █████████████████
  2019: ████████████████████  101 ████████████████████
  2020: ██████████████████   94 ██████████████████
  2021: ██████████████████   94 ██████████████████
  2022: █████████████████████  108 █████████████████████
  2023: █████████████████████  106 █████████████████████
  2024: ██████████████████████  113 ██████████████████████
  2025: ███████████████   76 ███████████████

In [140]:
# MÓDULO 16 - SALVANDO O DATSET LIMPO - ENRIQUECIDO COM NOVAS COLUNAS
# Fazer o Loard do RTL - Resultado Final (Arquivo CSV p/ o Power BI)

# Encondin = 'UTF-8-sig' - para garantir que os acentos sejam lidos corretamente no Power BI
#                          UTF-8 com BOM (Byte Order Mark) para compatibilidade total com o Power BI e Excel

df_limpo.to_csv(
    'base_rh_dia01.csv',    # Nome do arquivo de saída
    index=False,            # Não inclui o índice do DataFrame no CSV
    sep=';',                # Define o ponto e vírgula como separador de colunas
    encoding='UTF-8-sig',   # Codificação para garantir compatibilidade com acentos no Power BI
)

print('Base_rh_dia01.csv exportada com sucesso!')
print(f'    Colunas finas: {df_limpo.columns.tolist()}')
print(f'    Linhas       : {len(df_limpo)}')

Base_rh_dia01.csv exportada com sucesso!
    Colunas finas: ['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status', 'Ano_Admissao', 'Mes_Admissao', 'Trimestre', 'Tempo_de_casa_em_anos', 'Tempo_Casa_Anos', 'Faixa_Tempo_Casa']
    Linhas       : 1000

# MÓDULO 17 - EXERCÍCIO FINAL

# Cenário
#### O Gestor de RH da Industria Metalúrgica Catarinanse pediu 2 entregáveis: <br>   1 - A base de funcionário em Excel com "uma aba por departamento"; <br>   2 - Um relatório de tempo de casa pronto para o Power BI.

In [ ]:
# Carregamento da base_rh.csv para o processo de limpeza e análise
CAMINHO = r'C:\Users\ENG PC\turma-visualizacao-de-dados\alunos\jonatas_mag\Semana_04\base_rh.csv'

df = pd.read_csv(
    CAMINHO,
    sep=";",            #separador de colunas a ser usado
    encoding="cp1252",  #encode do windos para acentos
    decimal=","         #Separador de casas decimais
)

#Confirmação de carregamento e diagnóstico rápido dos dados
print('Dados Carregados')
print(f'Total de linhas e Colunas: {df.shape[0]}, {df.shape[1]}')
print()
print(f'A coluna Salário é: {df["Salario"].dtype}')

Dados Carregados
Total de linhas e Colunas: 1000, 10

A coluna Salário é: float64

### DIAGNÓSTICO GERAL PARA ANALÍSE RÁPIDO

In [174]:
# Diagnóstico geral da base
df.info()
print()
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

       ID_Funcionario       Salario        Idade
count     1000.000000   1000.000000  1000.000000
mean       500.500000   8579.951780    41.399000
std        288.819436   3657.365307    13.665817
min          1.000000   2000.710000    18.000000
25%        250.750000   5564.545000    30.000000
50%        500.500000   8571.135000    41.000000
75%        750.250000  11554.630000    53.000000
max       1000.000000  14954.510000    65.000000

### Relato de problemas encontrados:

##### Os 3 mais importantes que encontrei foram:<br> 1 - A coluna "Data_Admissao" no formato de texto (string) e precisa ser convertida em Datetime para poder extrair informações como ano, mês, tempo de casa, etc.<br> 2 - Criar colunas auxiliares para a extração de dados detalhados como Ano_Admissão, Mês_Admissão, Tempo_Casa_Anos, etc. para facilitar a análise e visualização dos dados.<br> 3 - Criar bases filtradas e enriquecidas para analise em Excell e criação de Dashboards no Power BI.

### CONVERTENDO srt EM Datatime - ANTES e DEPOIS

In [ ]:
# Antes da conversão:
print(f'Tipo ANTES : {df["Data_Admissao"].dtype}')
print(f'Valor antes: "{df["Data_Admissao"].iloc[0]}"') # .iloc[0] → acessa a primeira linha pelo índice
print()

# Trabalhamos em uma cópia para não alterar o df original
df_ok = df.copy()
# Sem isso, mudanças em df_ok afetariam o df original

# Mudando a coluna inteira
df_ok['Data_Admissao'] = pd.to_datetime(
    df_ok['Data_Admissao'],
    format='%d/%m/%Y',  # Formato da entrada
    errors='coerce'     # Datas inválidas viram NaT (Not a Time) em vez de erro
)

print(f'Tipo DEPOIS : {df_ok["Data_Admissao"].dtype}')
print(f'Valor depois: {df_ok["Data_Admissao"].iloc[0]}')
print(f'NaT gerados : {df_ok["Data_Admissao"].isna().sum()}')

Tipo ANTES : str
Valor antes: "13/08/2024"

Tipo DEPOIS: datetime64[us]
Valor depois: 2024-08-13 00:00:00
NaT gerados : 0

### FAZER A ANALISE DETALHADA DA Data_Admissao - ADD COLUNAS ESPECÍFICAS

In [178]:
# Criar colunas derivadas da Data de Admissão
df_ok['Ano_Admissao'] = df_ok['Data_Admissao'].dt.year
df_ok['Mes_Admissao'] = df_ok['Data_Admissao'].dt.month

# Calcular tempo de casa em anos
hoje_ts = pd.Timestamp.today()      # pd.Timestamp.today() → data atual no formato do pandas

# Subtração de datas = timedelta
df_ok['Tempo_Casa_Anos'] = ((hoje_ts - df_ok['Data_Admissao']).dt.days / 365.25).round(1)    # .dt.days → extrai a diferença em dias
df_ok['Faixa_Tempo_Casa'] = ((hoje_ts - df_ok['Data_Admissao']).dt.days / 365.25).round(1)   # / 365.25 → converte dias em anos
# .round(1) → arredonda para 1 casa decimal

# Resultado final para conferência
cols = ['Nome', 'Data_Admissao', 'Ano_Admissao', 'Mes_Admissao', 'Tempo_Casa_Anos', 'Faixa_Tempo_Casa']
df_ok[cols].head(6)

,Nome,Data_Admissao,Ano_Admissao,Mes_Admissao,Tempo_Casa_Anos,Faixa_Tempo_Casa
0,Julia Nunes,2024-08-13,2024,8,1.7,1.7
1,Sr. Gustavo Duarte,2017-04-29,2017,4,9.0,9.0
2,Srta. Mariana Cunha,2024-12-11,2024,12,1.4,1.4
3,Ana Sophia da Cruz,2019-06-16,2019,6,6.9,6.9
4,Dr. Nicolas Pinto,2019-03-29,2019,3,7.1,7.1
5,Marcela Costa,2024-07-23,2024,7,1.8,1.8

### OBTENDO A MÉDIA DE RETENÇÃO E TEMPO DE CASA POR DEPARTAMENTO

In [179]:
# Tempo médio de casa por departamento
media_depto = (
    df_ok
    .groupby('Departamento')['Tempo_Casa_Anos']
    .mean()
    .round(1)
    .sort_values(ascending=False)
    .reset_index()          # .reset_index() → converte o índice em coluna comum
)

maior = media_depto.set_index('Departamento')['Tempo_Casa_Anos'].idxmax()   # .idxmax() → retorna o NOME do índice com maior valor
menor = media_depto.set_index('Departamento')['Tempo_Casa_Anos'].idxmin()   # .idxmin() → retorna o NOME do índice com menor valor
print(f'→ Maior média de tempo de casa: {maior}')
print(f'→ Menor média de tempo de casa: {menor}')

→ Maior média de tempo de casa: RH
→ Menor média de tempo de casa: Financeiro

### GERANDO BASE PARA EXCEL - COMPLETA COM ABA ÚNICA

In [171]:
# Exportação simples: tudo em uma aba
df_ok.to_excel('base_rh_ok.xlsx', index=False, sheet_name='Funcionarios')
print('Base_rh_ok.xlsx (aba única) gerado!')

Base_rh_ok.xlsx (aba única) gerado!

### GERANDO BASE PARA EXCEL/POWER BI - COMPLETA COM ABA POR DEPATAMENTO

In [172]:
# Exportação avançada: uma aba por departamento
with pd.ExcelWriter('base_rh_por_depto_ok.xlsx', engine='openpyxl') as writer:

    # Aba 1: dataset completo
    df_ok.to_excel(writer, sheet_name='Todos', index=False)
    print('  Aba Todos: todos os registros')

    # df['Departamento'].unique() → lista de departamentos sem repetição
    # sorted() → ordena em ordem alfabética
    for depto in sorted(df_ok['Departamento'].unique()):

        # Filtrar só os funcionários desse departamento
        df_depto = df_ok[df_ok['Departamento'] == depto]

        # Limite do Excel: nomes de aba têm no máximo 31 caracteres
        nome_aba = depto[:31]

        df_depto.to_excel(writer, sheet_name=nome_aba, index=False)
        print(f'  Aba "{nome_aba}": {len(df_depto)} registros')

print('\n Base_rh_por_depto_ok.xlsx gerado!')

  Aba Todos: todos os registros
  Aba "Financeiro": 189 registros
  Aba "Logística": 156 registros
  Aba "Produção": 182 registros
  Aba "RH": 166 registros
  Aba "TI": 147 registros
  Aba "Vendas": 160 registros

 Base_rh_por_depto_ok.xlsx gerado!